spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/mydb?useSSL=false
    username: sboot
    password: sboot
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
server:
  port: 2941