spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/mydb?useSSL=false
    username: sboot
    password: sboot
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
server:
  port: 2941
